fix: stuff

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -6,9 +6,9 @@
 FROM ubuntu:noble
 
 RUN if id "ubuntu" &>/dev/null; then \
-            echo "Deleting user 'ubuntu' for noble" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for noble"; \  
+            echo "Deleting user 'ubuntu' for noble" && userdel -f -r ubuntu || echo "Failed to delete ubuntu user for noble"; \
         else \
-            echo "User 'ubuntu' does not exist for noble"; \ 
+            echo "User 'ubuntu' does not exist for noble"; \
     fi
 
 ENV LANG="C.UTF-8"
@@ -19,24 +19,19 @@ ARG DEBIAN_FRONTEND="noninteractive"
 # Merging the mutiple layers to reduce the size of the image slightly
 RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     # Restore man command
-    && yes | unminimize 2>&1 \ 
+    && yes | unminimize 2>&1 \
     # Install basic build tools
     && apt-get upgrade -y \
     && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
         make \
         unzip \
-        # The tools in this package are used when installing packages for Python
         build-essential \
         swig3.0 \
-        # Required for PostgreSQL
         libpq-dev \
-        # Required for ts
         rsync \
         zip \
         jq \
-        # By default pip is not available in the buildpacks image
         python3-pip \
-        #.NET Core related pre-requisites
         curl \
         gettext \
         inotify-tools \
@@ -50,18 +45,11 @@ RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
     && apt-get update \
     && apt-get -y install build-essential cmake cppcheck valgrind clang lldb llvm gdb python3-dev \
     # Install tools and shells not in common script
-    && apt-get install -yq vim vim-doc software-properties-common libsecret-1-dev \
+    && apt-get install -yq vim-tiny software-properties-common libsecret-1-dev \
     # Clean up
-    && apt-get autoremove -y && apt-get clean -y \
-    # Install and setup fish
-    && apt-get install -yq fish \
-    && FISH_PROMPT="function fish_prompt\n    set_color green\n    echo -n (whoami)\n    set_color normal\n    echo -n \":\"\n    set_color blue\n    echo -n (pwd)\n    set_color normal\n    echo -n \"> \"\nend\n" \
-    && printf "$FISH_PROMPT" >> /etc/fish/functions/fish_prompt.fish \
-    && printf "if type code-insiders > /dev/null 2>&1; and not type code > /dev/null 2>&1\n  alias code=code-insiders\nend" >> /etc/fish/conf.d/code_alias.fish \   
-    # Remove scripts now that we're done with them
-    && apt-get clean -y
+    && apt-get autoremove -y && apt-get clean -y
 
-# Default to bash shell (other shells available at /usr/bin/fish and /usr/bin/zsh)
+# Default to bash shell
 ENV SHELL=/bin/bash \
     DOCKER_BUILDKIT=1
 
